version: '3.8'

services:
  postgres:
    container_name: store_db
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user_password
      POSTGRES_DB: user_database
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    networks:
      - postgres
    restart: unless-stopped
    volumes:
      - postgres:/data/postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:

